Repository IBM-Design/design-website, pull requests merged in 2019-04, with the labels that each got.

#366 Image_3 update on Teams Page
  src/content/teams/images/Image_3.jpg
Labels: type: dev 🤖

#365 Update to the Watson logo image
  src/content/teams/images/Image_10.jpg
Labels: type: dev 🤖

#369 Fix:App switcher is linking to next.carbon
  src/components/SiteHeader/SiteHeader.js
Labels: status: ready for review :eyes:

#375 Updated Carbon URL
  src/content/practices/practices.md
Labels: status: ready for review :eyes:

#371 fix(homepage-video): add 5 sec preview video for a11y
  src/components/Video/Video.js
  src/content/index.md
Labels: status: one more review :eyes:
